name: mlio-devel
channels:
  - conda-forge
dependencies:
  - arrow-cpp=0.16.0
  - aws-sdk-cpp=1.7
  - cmake=3.15
  - compilers
  - doxygen=1.8
  - libiconv=1.15
  - libopencv=4.2.0
  - libprotobuf=3.11.0
  - ninja=1.9.0
  - pytest=5.4.1
  - python=3.7
  - tbb-devel=2019.8
  - zlib=1.2
